# +-----------------------------------------------------
# |         SPRING COMMON CONFIGURATION
# +-----------------------------------------------------
spring:
  rabbitmq:
    host: ${SERVER_BROKER_HOSTNAME:localhost}
    port: 5672
    username: ${SERVER_BROKER_USERNAME:spike}
    password: ${SERVER_BROKER_PASSWORD:Spike2021++}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2

# +-----------------------------------------------------
# |         EUREKA CLIENT CONFIG
# +-----------------------------------------------------
eureka:
  instance:
    hostname: ${SERVER_DISCOVERY_HOST:server-discovery}
  client:
    region: default
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:7071/eureka}
    registry-fetch-interval-seconds: 5

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /monitor/actuator
      exposure:
        include: "*"
