# +-----------------------------------------------------
# |         SPRING COMMON CONFIGURATION
# +-----------------------------------------------------
spring:
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: 5672
    username: "${RABBITMQ_USER:spike}"
    password: "${RABBITMQ_PASS:Spike2021++}"
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2

# +-----------------------------------------------------
# |         EUREKA CLIENT CONFIG
# +-----------------------------------------------------
eureka:
  instance:
    hostname: ${EUREKA_HOST:server-discovery}
  client:
    region: default
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:7071/eureka}
    registry-fetch-interval-seconds: 5

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /monitor/actuator
      exposure:
        include: "*"
