server:
  port: 7071

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:7071/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
management:
    server:
      port: 6071