server:
  port: 8081
  servlet:
    context-path: /bills

spring:
  application:
    name: svc-bills
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_BILLS_HOST:localhost}:3301/billsdb
    username: bills
    password: bills2021++

events:
  rpc:
    products:
        exchange: products-exchange-events
        queue: products-queue-request
        routing-key: products-events-key
    clients:
        exchange: clients-exchange-events
        queue: clients-queue-request
        routing-key: clients-events-key

management:
    server:
      port: 6181

logging:
  level:
    org.springframework.web: DEBUG
    co.com.demo.bills: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss a} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
